import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
// Note: @astrojs/sitemap has a bug with Astro 4.16, so using custom script instead
// import sitemap from "@astrojs/sitemap";

export default defineConfig({
  site: "https://aubigny.wine",
  output: "static",
  integrations: [],
  // Sitemaps generated by scripts/generate-sitemaps.mjs at build time
  // integrations: [sitemap()],
  vite: {
    plugins: [tailwindcss()],
  },
  image: {
    service: {
      entrypoint: "astro/assets/services/sharp",
    },
  },
  build: { inlineStylesheets: "auto" },
});
